### ISSUE TITLE
Keeps updating every time despite being the same version

### ISSUE THREAD

**Issue by wrjlewis** [vitorgalvao/alfred-workflows#112]
#### Setup info

* Workflow name: notion-search-alfred-workflow
* Workflow version: 0.3.2
* Alfred version: 4
* macOS version: 10.15.5

Using the latest version of https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater

#### Description of issue

An update is triggered every time. 

I expect no update to be triggered because my installed version of the workflow (0.3.2) is the same as the [master info.plist](https://github.com/wrjlewis/notion-search-alfred-workflow/blob/master/info.plist) version (0.3.2).

[Screenshots](https://imgur.com/a/goaUtZO)

#### Debugger output

```
[10:22:16.446] Notion Search[Script Filter] Passing output 'XXX' to Run Script
```

**Comment by vitorgalvao** [comment]
You’re not linking to the `info.plist`, you’re linking to *a webpage*. You need to use https://raw.githubusercontent.com/wrjlewis/notion-search-alfred-workflow/master/info.plist

**Comment by vitorgalvao** [comment]
> Using the latest version of https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater

Never say “latest” but always the exact version. “Latest” doesn’t help debugging (how do I know you’re really on the latest version?) or people who come after.

There’s a reason I ask for specific versions right on the template, which is for the version of my Workflow you’re requesting help for, not yours. The point of asking for a version is narrowing down where the issue lies; knowing your Workflow’s version makes no difference.

**Comment by wrjlewis** [comment]
Thanks for being so explicit. I've updated my workflow accordingly.
