### ISSUE TITLE
not work after upgrade to latest version

### ISSUE THREAD

**Issue by addozhang** [vitorgalvao/alfred-workflows#124]
#### Setup info

* Workflow name: CalmNotifications
* Workflow version: latest version in github
* Alfred version: 4.3.1
* macOS version: 10.15.4

#### Description of issue

not work after upgrade

#### Debugger output

[09:39:53.950] Logging Started...
[09:39:55.034] CalmNotifications[Script Filter] Queuing argument ''
[09:39:55.401] CalmNotifications[Script Filter] Script with argv '' finished
[09:39:55.403] STDERR: CalmNotifications[Script Filter] /Users/addo/Library/Application Support/Alfred/Workflow Data/com.vitorgalvao.alfred._sharedresources/bin/calm-notifications:20:in `grab_dnd_xml': undefined method `text' for nil:NilClass (NoMethodError)
	from /Users/addo/Library/Application Support/Alfred/Workflow Data/com.vitorgalvao.alfred._sharedresources/bin/calm-notifications:41:in `status_dnd'
	from /Users/addo/Library/Application Support/Alfred/Workflow Data/com.vitorgalvao.alfred._sharedresources/bin/calm-notifications:98:in `<main>'
[09:39:55.404] CalmNotifications[Script Filter] {"items":[{"title":"Turn it on","subtitle":"Stop notifications from going through until tomorrow","arg":"on"}]}

```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

**Comment by paw-lu** [comment]
Same!
Thanks for reporting @addozhang !

**Comment by vitorgalvao** [comment]
[See the forum post](https://www.alfredforum.com/topic/10916-calmnotifications-—-toggle-do-not-disturb/?tab=comments#comment-56259). It now only works on Big Sur, but you can still [download the old version](https://raw.githubusercontent.com/vitorgalvao/alfred-workflows/3277467723793e081adbdcf561e966d65c7b1482/CalmNotifications/CalmNotifications.alfredworkflow) (delete the `OneUpdater` node so you’re no longer warned of updates).

I agree I rushed in posting the new version, but now it’s difficult to go back. Because I don’t employ analytics, I have no idea what macOS version users of my tools are in (or how many users I have, even).

I distribute and support all my tools for free (donations are incredibly rare) so tend to only support whatever macOS version I’m on. Running VMs to test other versions would be a huge time sink for no gain.

If I think of an acceptable solution for this transition, I’ll implement it. For now, use the older version and redownload when you upgrade to Big Sur (if ever).

**Comment by addozhang** [comment]
@vitorgalvao got it. Tks.

**Comment by paw-lu** [comment]
no worries @vitorgalvao—downgrading is easy 😄
thanks for the great workflow!

**Comment by addozhang** [comment]
one more thing, disable new version checking by setting 'frequency_check' to 999 😄
