### ISSUE TITLE
Can I make pa work with Firefox?

### ISSUE THREAD

**Issue by hapimp** [vitorgalvao/alfred-workflows#130]
#### Setup info

* Workflow name: pa
* Workflow version: 
* Alfred version: 4.3.4
* macOS version: 21.8
* Architecture: Intel

#### Description of issue

I'm using Firefox 89.0 and cannot get pa-command to work. Went through closed issues and see there was a similar issue with Brave at some point that had to do with the browser and not the workflow, so I'm afraid my issue is similar.

Still: Does Firefox work for others and are there any steps I can take to make it work for me?

#### Debugger output

```
[07:26:20.954] PinPlus[Keyword] Processing complete
[07:26:20.958] PinPlus[Keyword] Passing output '' to Run Script
[07:26:21.309] STDERR: PinPlus[Run Script] /Users/esbenhardenberg/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E47185FC-AF37-4BDB-B474-4054413773DD/run_bookmarklet.js: execution error: Error: Error: You need a supported browser as your frontmost app (-2700)
[07:26:21.310] PinPlus[Run Script] Processing complete
[07:26:21.313] PinPlus[Run Script] Passing output '' to Run Script
```

**Comment by vitorgalvao** [comment]
No, it’s not possible to have it work with Firefox, because Firefox doesn’t support AppleScript and that is necessary to get the necessary information (title and URL of frontmost tab). That is why Firefox is always excluded from Alfred Workflows.

[The bug tracking the lack of AppleScript in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=125419) is two decades old, but you can still try to make your voice heard there. I wouldn’t hold my breath: I’ve spoken with Firefox people—both online and in person—and they either had no idea what AppleScript is (despite most of their developers ostensibly using macOS) or they said it was a power-user feature (completely missing the point that power users make tools for other people and that not adding the feature means fewer people who use Firefox).

I’ll gladly add Firefox support to all my Workflows if they ever add AppleScript support. But that seems more unlikely every day.
