### ISSUE TITLE
Automatically remove .alfredworkflow file from Downloads Folder

### ISSUE THREAD

**Issue by chrisgrieser** [vitorgalvao/alfred-workflows#131]
only a very minor thing that I would implement. Maybe as an option. Very great and useful work otherwise, thanks for that!

**Comment by vitorgalvao** [comment]
Please don’t delete the template; it’s there for a reason. I don’t know what Workflow you’re talking about.

Do you mean “after something has been auto-updated by `OneUpdater`”? There’s no good way to do that because after telling macOS to open the Workflow, we relinquish control.

There are workarounds, like downloading to a temporary directory instead. But I avoided that because what if the user decides to not install at that time and wants to do it later instead? In practice I don’t know if that’s a common occurrence, though.

No promises yet, but I’ll give it a thought. I’m not opposed to the idea, but I have to think it through.

> Very great and useful work otherwise, thanks for that!

Thank you for the kind words.

**Comment by chrisgrieser** [comment]
Oh, I didn't notice that this repository is for all of your workflows, sorry. Yes, I mean OneUpdater.

I assume that if desired, one can always open the Trash (or the Browser Download history) for the rare cases where the suer does not install the file but wants to do it later?

**Comment by vitorgalvao** [comment]
> I assume that if desired, one can always open the Trash

The problem is trashing the Workflow at the right time. As I said, after telling macOS to open the Workflow, we relinquish control.

And downloading a Workflow to trash immediately isn’t a good experience.

> or the Browser Download history

There’s no browser download history; the download doesn’t use a browser, it’s direct.
