### ISSUE TITLE
Add support for Universal Actions

### ISSUE THREAD

**Issue by chrismessina** [vitorgalvao/alfred-workflows#134]
#### Setup info

* Workflow name: MarkdownTransform
* Workflow version: v21.10
* Alfred version: 4.5.1 [1255]
* macOS version: macOS 11.5.1 (20G80)
* Architecture: Intel

#### Description of issue

I'd like to propose adding Universal Action blocks to this workflow to make it easier to take a Text selection via a hotkey and run it through your Markdown converter.

I've made the changes on my end, and would like to contribute them upstream (see [attached](https://github.com/vitorgalvao/alfred-workflows/files/6958361/MarkdownTransform.zip)). 

![image](https://user-images.githubusercontent.com/22610/128795738-376913f1-4390-4271-a974-eb6027d2ef2d.png)

**Comment by vitorgalvao** [comment]
Sure. I hadn’t added it yet because I haven’t gone though all my Workflows to think which would benefit from Universal Actions. Open to further suggestions.

I don’t take packaged Workflows, though, only code PRs. I need to see the code in context before merging it.

I’ve added the Universal Triggers to the newest release (already out).

Thank you for the recommendation.

**Comment by chrismessina** [comment]
Thanks for the fast turnaround! 

In the future, how would I contribute a code PR for a workflow? Do you have a contribution guide?

**Comment by vitorgalvao** [comment]
> how would I contribute a code PR for a workflow?

1. Change the Workflow.
2. Clone the repo.
3. Replace the relevant parts from your the repo’s Workflow with your modifications.
4. Commit, push, open PR.

That way I can evaluate the code, merge, then make a new release.

Alternatively, I’ll copy the changes locally and release from there, because it’s way simpler for my method.

But for node additions, I’d rather have the request.

**Comment by chrismessina** [comment]
Cool. I sometimes forget that Workflows are basically just plists.

**Comment by vitorgalvao** [comment]
> Workflows are basically just plists

Which is why I prefer to have a request when it’s just adding nodes. For code changes, the PR is fine. Though again, I may pull and commit locally.
