### ISSUE TITLE
403 Error, Imgur is temporarily over capacity

### ISSUE THREAD

**Issue by pavzagor** [vitorgalvao/alfred-workflows#144]
https://user-images.githubusercontent.com/41447040/151697594-24a1e864-f56f-4a1f-8490-74736a9a6b0f.mp4

**Comment by pavzagor** [comment]
Latest version (22.1)

Seems to be something with the keys, but didn't find how to change them

**Comment by vitorgalvao** [comment]
I don’t understand what you don’t get about the error. The problem is external and temporary. I don’t control or have any affiliation with imgur. Stop and try again later; right now you’re just straining their servers further.

Also, please don’t ignore the template that’s in place. The information I ask is the information I need to debug.
