### ISSUE TITLE
SynAnt closes itself when using cmd+enter/alt+enter

### ISSUE THREAD

**Issue by goerwin** [vitorgalvao/alfred-workflows#145]
#### Setup info

* Workflow name: SynAnt
* Workflow version: 21.1
* Alfred version: 4.6.2
* macOS version: 11.6.2
* Architecture: Intel

#### Description of issue

When I try to cmd+enter to search for the synonyms of an list item, it closes the alfred window and can't see the results.
I can fix this by enabling "Don't close the Alfred Window on actioning result" checkbox, but I think it should be the default.

**Comment by vitorgalvao** [comment]
I can’t reproduce the problem; it always worked fine come me because it opens the window right away. I’d be interested in seeing a [video](https://support.apple.com/en-us/HT208721) of the behaviour with the [debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) open and visible.

But activating this doesn’t make a difference to me, so if it fixes it for you, I have indeed made it the default (just released).
