### ISSUE TITLE
macupdater_client does not exit if scans too frequent, hangs scripts

### ISSUE THREAD

**Issue by luckman212** [vitorgalvao/alfred-workflows#158]
Hi @vitorgalvao 

I started using `/Applications/MacUpdater.app/Contents/Resources/macupdater_client scan` in some automation scripts. I didn't know about this CLI! 

One problem, as I was testing, obviously I was running the `scan` parameter more often than normal, so I hit this:

![image](https://user-images.githubusercontent.com/1992842/186663662-0a8084b2-c111-43f0-bc5e-f862913d04f4.png)

The problem here is, even after clicking **OK**, the `macupdater_client` process does not exit, so the script hangs indefinitely. I imagine this could/would affect the [Alfred workflow](https://github.com/core-code/MacUpdater-Alfred-Workflow/) as well.

![image](https://user-images.githubusercontent.com/1992842/186663893-9ccd975b-5c05-470f-be57-aa2d7fe3b819.png)

**Comment by vitorgalvao** [comment]
Nice catch. That’s something which should be addressed in the MacUpdater CLI. It won’t affect the Workflow because it handles updates, not the scanning (that should be left to MacUpdater’s scheduling). If you [contact MacUpdater](mailto:feedback@corecode.io), which I guess you might’ve done already, someone will take a look. Though it seems like a low priority issue, I imagine it doesn’t happen often.

Tangentially, note the MacUpdater Workflow has [its own repo](https://github.com/core-code/MacUpdater-Alfred-Workflow). Thank you for the concern.

**Comment by luckman212** [comment]
Sure, I just reported it via email to support. Thanks @vitorgalvao

**Comment by core-code** [comment]
thanks for the bug report. we've addressed this now and the fix will be in the next public release of #MacUpdater (build number > 13887)

can't say if there will be another 2.2.2 build or if the next release will already be version 2.3
