### ISSUE TITLE
Make it work with Orion Browser?

### ISSUE THREAD

**Issue by pvalfar** [vitorgalvao/alfred-workflows#162]
Hi.

Any idea how I can edit the bash script to make this workflow work in Orion Browser?
Simply setting Orion as a new front browser did not work.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/108862898/203854222-b8bd0816-f5cb-485b-9235-45dcb0ce4f9b.png">

**Comment by vitorgalvao** [comment]
Please don’t skip the issue template. It’s there so I don’t have to guess which Workflow you’re referring to.

Orion isn’t supported because they have insufficient AppleScript support. They don’t allow everything Safari does, like tab indexes. You’ll have to ask them to add better support.

That said, the next version of the workflow will make it better for all browsers without good AppleScript support, like Firefox.
