### ISSUE TITLE
Is there any way to keep the workflow environment variables when updating？

### ISSUE THREAD

**Issue by Nauxscript** [vitorgalvao/alfred-workflows#166]
#### Setup info

* Workflow name: OneUpdater
* Alfred version: 4
* macOS version: 12.6
* Architecture: (Intel or Apple Silicon) Apple M1 pro 

#### Description of issue
hey, thanks for your workflows, its amzing and helpful!

I had made [a workflow](https://github.com/Nauxscript/alfred-open-port) and use the OneUpdater workflow to implement auto-update. but i found that every time the workflow update, the workflow environment variables will be covered and my workflow have a custom variable set by user, so when user updated the workflow, the variable they set is gone. 

Is there any way to keep the workflow environment variables when updating？

**Comment by vitorgalvao** [comment]
If the variable is being overwritten, it’s because when the workflow opens to be updated, the user is unticking this checkbox on the bottom left:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1699443/209682166-6cac3334-9ebf-4c02-bb18-2f608ff77739.png">

Leave it ticked and the variables will be preserved.

**Comment by Nauxscript** [comment]
Thank you for your reply! I will try it.

**Comment by Nauxscript** [comment]
hey, thank for your previous answer.

I have tried the way you mentioned before, but it doesn't seem to work.after ticking `Migrate my workflow customisations`, the local environment variables still being overwritten. 

![image](https://user-images.githubusercontent.com/13010589/225259934-06c25dba-5d4f-4966-8aa9-6d082d094dc9.png)

**Comment by vitorgalvao** [comment]
The variable needs to exist in the first place. If you don’t want the *value* to be exported, tick the checkbox. This isn’t related to OneUpdater.

In Alfred 5 you should be using [Workflow Configuration](https://www.alfredapp.com/help/workflows/workflow-configuration/) instead of Workflow Environment Variables for things users are meant to change.
