### ISSUE TITLE
Adding selection to the WebScreenshot workflow.

### ISSUE THREAD

**Issue by politicus** [vitorgalvao/alfred-workflows#17]
Great idea Vitor!

I installed it but didn't used it as it wanted to be able to select one part of my screen not take a screenshot of all the screen. 

Is such a feature on your roadmap?

**Comment by vitorgalvao** [comment]
I’m a bit confused by the title and content of the request (they seem to contradict).

To be clear, are you asking for an equivalent to <kbd>⌘</kbd><kbd>⇧</kbd><kbd>3</kbd>?

**Comment by politicus** [comment]
I didn't knew screenshot could only mean "all the screen".

I should have said "being able to upload to Imgur a selected area of the screen".

**Comment by vitorgalvao** [comment]
But that’s exactly what it does. In fact, you can *only* select an area of the screen. The workflow doesn’t support taking screenshots of the whole screen.

**Comment by politicus** [comment]
So this is perfect. 
Case closed ;-)

**Comment by Jyqft** [comment]
Just curious though, why does the WebScreenshot workflow not have a CMD+SHIFT+3 counterpart? @vitorgalvao

**Comment by vitorgalvao** [comment]
Though I can add it, I haven’t done so yet for a number of reasons.

<kbd>⌘</kbd><kbd>⇧</kbd><kbd>3</kbd> is way less common and useful. Particularly if you want a workflow to quickly upload screenshots, it’s unlikely you’ll want the whole screen. For the rare cases when you do want it, with <kbd>⌘</kbd><kbd>⇧</kbd><kbd>4</kbd> you can essentially achieve the same the same effect by selecting the whole screen (though yes, you might not find it ideal).

So we start with an issue of practicality in implementation. I use [a third-party script](https://github.com/jomo/imgur-screenshot) to upload the screenshots<sup>1</sup>. It lacked some things I wanted for this workflow, so [I’ve been submitting them](https://github.com/jomo/imgur-screenshot/pulls?q=is%3Apr+author%3Avitorgalvao+is%3Aclosed) and [discussing others](https://github.com/jomo/imgur-screenshot/issues/created_by/vitorgalvao).

Most (if not all) of those I could’ve just done on my end, but I haven’t for two main reasons: it’s actually better to just contribute to the main tool, making it not only more robust for this workflow but for everyone else that uses it in other capacities, and because I’d be working around it instead of with it, making my own code and maintenance that much harder.

<kbd>⌘</kbd><kbd>⇧</kbd><kbd>3</kbd>, which is something I considered before, would actually have been a bore to implement, in the previous iteration. However, with the refactoring I made recently to add resampling, it would actually be trivial to implement. The reason I haven’t done so is clarity. Though I build workflows to scratch my own itches (not always, as some were made by request, and others for proofs of concept or experiments to push Alfred’s limitations to their limits), I try to design them to be as clear and usable by others as possible<sup>2</sup>.

When you have a bunch of Alfred keywords, being clear with intent is easy. With hotkeys, not so much. It’s fine if you as a user have to look at the left side of workflows (keywords, script filters) to understand *what does what*, as those sections are built in a way that you can understand them by reading their non-code contents. However, If you’re forced to read the right side of workflows (a bunch of code blocks) and look at *how things work*, that is a worse experience (and may be terrifying if you don’t understand and are afraid you’ll mess up the code).

Hotkeys are weird in that regard. They are on the left side and activate other options, but there’s no way to understand what they do unless you look at the right side. For that reason, I try to make it so that if I have a hotkey connecting somewhere, I’ll have at least a keyword or script filter connecting there as well, something that gives you a clue. In this case, however, that wouldn’t make sense, as the whole point is to be able to do it fast with a hotkey. But I already have two hotkeys that you need to know, and adding support for <kbd>⌘</kbd><kbd>⇧</kbd><kbd>3</kbd> would add two more (two because of resampling), and I feel that will make it more complex in a way that isn’t worth it.

So I’ll add the option if there’s a demand for it, but likely<sup>3</sup> won’t otherwise.

That’s probably way more context than expected, but I hope it makes sense as to why this works the way it does currently.

---

<sup>1</sup> I used [another app](https://github.com/FigBug/imguru) for [months before actually working on this for release](http://www.alfredforum.com/topic/8285-upload-clipboard-image/?p=41258). That workflow was really rough in many areas (like detecting errors) but worked well enough, which is why is just let it linger on for my own needs before working on it for this release,

<sup>2</sup> Which partially explains why some are unreleased, like the old version of this one. Others are unreleased either because they are so specific to my needs they would be of value to virtually nobody else, or because they’re so simple (but still useful) that even non-coders could easily recreate them.

<sup>3</sup> Still thinking about it.
