### ISSUE TITLE
[WebScreenshot] Latest version doesn't seem to work

### ISSUE THREAD

**Issue by Jyqft** [vitorgalvao/alfred-workflows#18]
I got the latest version of the workflow, and whenever I press the hotkeys or execute the file actions, nothing happens. I took a look at the error log, and I found this:

    [INFO: alfred.workflow.trigger.hotkey] Processing output 'alfred.workflow.action.script' with arg ''
    [ERROR: alfred.workflow.action.script] usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix

**Comment by vitorgalvao** [comment]
You need to be more specific. There are over 20 workflows in this repo, and I have no idea which you’re referring to.

**Comment by Jyqft** [comment]
Sorry bout that, I thought I was on the issues page for the WebScreenshot workflow.

**Comment by vitorgalvao** [comment]
You are, it’s just that it’s also the issues page for all my other workflows.

I’ll still need more information (since it works for me), but lets go in small steps:

1. Which OS X version are you using?
2. If you [open a terminal](http://youtu.be/OijYweDKhz4) and execute `mktemp`, what’s the output?

**Comment by Jyqft** [comment]
1. Mac OS X 10.10.5 (14F1509)
2. The exact output is as follows:

    usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix

**Comment by vitorgalvao** [comment]
Ah, so it seems the behaviour of `mktemp` changed in El Capitan. What is, then, the output of `mktemp -t 'webscreenshot'`?

**Comment by Jyqft** [comment]
/var/folders/lz/b52djpjn7r9g4dkkpdd8krj80000gn/T/webscreenshot.k3Dgdbh4

**Comment by vitorgalvao** [comment]
Great! In that case, get [the new version](https://github.com/packal/repository/raw/master/com.vitorgalvao.alfred.webscreenshot/webscreenshot.alfredworkflow), which has the fix. If it doesn’t fix it, please report back.

**Comment by Jyqft** [comment]
That was really fast. Thanks, that fixed it!

I gotta ask though, what does the new feature do? Something about resampling the image?

**Comment by vitorgalvao** [comment]
Thank you for showing the output of Alfred’s debugger right in the top post. That made it faster to figure out what the issue was.

As for resampling, that’s only relevant if you’re on a retina screen. See [this post](https://cloudup.com/blog/the-retina-screenshot-problem) (only need to read the first half) for an explanation of the problem.
