### ISSUE TITLE
RunCommand is not compatible with latest 3.0.3 alfred

### ISSUE THREAD

**Issue by a-x-** [vitorgalvao/alfred-workflows#24]

**Comment by vitorgalvao** [comment]
Ah, yes, it’s using a pre-release feature. Well, since it only got the ability to auto-update in this version, there’s no point in reverting now, since you’d need to manually download on the next version anyway.

You need either update to the pre-release of Alfred, or only install the new version of RunCommand after the current pre-release is stable.
