### ISSUE TITLE
Error message when adding file as template, template file can not be deleted

### ISSUE THREAD

**Issue by workflowsguy** [vitorgalvao/alfred-workflows#35]
Follwing issue #34 [(https://github.com/vitorgalvao/alfred-workflows/issues/34)],
I have upgraded to 10.11.6. Here there are other issues.

Two issues I have encountered:

1.) Creating templates from file or directory works in principle, but there is an error message displayed every time.

`Error on line 6: SyntaxError: Unexpected identifier 'i'. Expected either 'in' or 'of' in enumeration syntax.`

Pressing Edit opens Notificator.app in the Script Editor.

2.) Deleting Templates from "tml" with pressing Alt+Enter does not work. With "tme" I can see that the file/directory is still in the templates folderand is still listed the next time I enter "tml"

**Comment by vitorgalvao** [comment]
[I mentioned the fix for `1` in the other issue](https://github.com/vitorgalvao/alfred-workflows/issues/34#issuecomment-308155537).

Can’t reproduce `2`, especially if you don’t give me an actual error.

**Comment by workflowsguy** [comment]
Because there is no error!
When trying to delete a template, this is the output in debugger:

```
Starting debug for 'TemplatesManager'

[2017-06-15 09:43:17][input.scriptfilter] <?xml version='1.0'?><items>
<item uuid='0' arg='0' valid='yes'>
<title><![CDATA[Testverzeichnis1]]></title>
<icon>icon.png</icon>
</item>
</items>
[2017-06-15 09:43:22][input.scriptfilter] Processing output of 'action.script' with arg '0'

```

**Comment by vitorgalvao** [comment]
> Because there is no error!

In that case there’s nothing I can do. As I said, I cannot reproduce this. It works fine for me and no one else has the issue. It follows that it’s likely to be some oddity with your setup. I’d delete the Workflow and all data (your templates dir if custom, as well as `~/Library/Application Support/Alfred 3/Workflow Data/com.vitorgalvao.alfred.templatesmanager`) and try again.

Otherwise, I’d only be able to know what’s wrong by looking at your machine/setup.
