### ISSUE TITLE
dnd: turn it on doesn't work with High Sierra

### ISSUE THREAD

**Issue by josefglatz** [vitorgalvao/alfred-workflows#45]
the workflow shows, "turn it off", but nothig happens. Even no debug entry in the workflow

**Comment by vitorgalvao** [comment]
I‘m not yet on High Sierra, so I can’t test.

You can [try this](https://apple.stackexchange.com/a/244130/26865) in the meantime.

If I get a PR/suggestion with a different method that works on Sierra and High Sierra, I’ll include it. Otherwise I’ll look at this after I upgrade *if* I can reproduce.
