### ISSUE TITLE
Yes Yes Yes! But ....PathFinder?

### ISSUE THREAD

**Issue by filipgoc** [vitorgalvao/alfred-workflows#71]
* Workflow name: RightClick
* Workflow version: 1.1.2
* Alfred version: latest
* macOS version: 10.13.6

I love this workflow! Yes. I spent countless hours trying to do this (and NOT the native solution that clicks where the mouse is... that one is useless.) 

I missed this one from my Windows days so much.
Thank you so much!
Also, my girlfriend has pain in her arm - this will greatly reduce the strain. 

That being said... I despise Finder and do not use it. Is there any chance this could be adopted for **PathFinder**?

**Comment by vitorgalvao** [comment]
> Alfred version: latest

Tip when debugging: never say “latest” but always the exact version. When you say “latest” I don’t know if you mean the latest beta or stable version, nor do I know if you’re actually on the newest version. You may think you’re up to date but be mistaken, or might be a version behind because the auto-update hasn’t kicked yet, or I may not be on what I think is the latest version but isn’t, or a multitude of other reasons. It also does not help someone who comes later with the same issue, as they’ll have no idea if their version matches yours.

> I love this workflow!

That makes me glad.

> my girlfriend has pain in her arm - this will greatly reduce the strain.

And this even more!

> I spent countless hours trying to do this

So did I! And it pains me that there was a time that with each macOS version, Apple broke it a little more.

> Is there any chance this could be adopted for **PathFinder**?

But unfortunately, the answer to this is “I don’t know”. The code as is works in more apps than the Finder (another user asked), but since I haven’t used PathFinder in years, I can’t say if they support the feature. They do have (had?) decent AppleScript support, though, so it’s definitely a possibility. The best place to ask would be their forums. Here’s the relevant code I’m using:

```applescript
tell application "System Events" to set frontApp to name of first process whose frontmost is true

tell application "System Events"
  tell application process frontApp
    set _selection to value of attribute "AXFocusedUIElement"
    tell _selection to perform action "AXShowMenu"
  end tell
end tell
```

If from the forums you get the relevant code to make this work in PathFinder, do let me know and I’ll update the Workflow!

**Comment by filipgoc** [comment]
Hi,
Thanks for the pointers! I'll most likely give it a try. 

I just can't go back to finder (even though I kind of hate pathfinder as it's quite unstable and has memory leaks and crashes multiple times a day... All I do is complain :-) )

---

> when debugging: never say “latest”

Hehe. I figured it was fine since I was not reporting a bug but basically feature requesting ;-)
