### ISSUE TITLE
MachineClean: "The workflow you are trying to import is invalid."

### ISSUE THREAD

**Issue by GandalfSaxe** [vitorgalvao/alfred-workflows#81]
#### Setup info

* Workflow name: MachineClean
* Workflow version: Commit 43b1293 "MachineClean: Updated for Alfred 4"
* Alfred version: 4.0.3
* macOS version: macOS 10.15 beta (19A501i)

#### Description of issue

Download `MachineClean.alfredworkflow` from [here](https://github.com/vitorgalvao/alfred-workflows/blob/master/MachineClean/MachineClean.alfredworkflow), I run it, get error `The workflow you are trying to import is invalid.`:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/12127864/61227758-379a5300-a725-11e9-9002-a7a7f3543ccf.png">

#### Debugger output

Didn't get any information out of the debugger. I set it to `All information` + `All workflows` but got nothing. Let me know if I can obtain logs in any other way.

**Comment by vitorgalvao** [comment]
I’ve deleted and [redownloaded](https://raw.githubusercontent.com/vitorgalvao/alfred-workflows/master/MachineClean/MachineClean.alfredworkflow) (try that link), and can’t reproduce.

Seems like a Catalina beta. By all accounts I’ve seen, this year the macOS public betas are more unstable than ever, and I’ve even heard reports that Apple developers recommend the public don’t install them. As such, unless a bug is reproducible on Mojave I won’t be diagnosing it until Catalina is out of beta, because I won’t be installing it before then and have no way to test either way.
