### ISSUE TITLE
Is it possible to keep the workflows backward compatible with Alfred 3?

### ISSUE THREAD

**Issue by meflouu** [vitorgalvao/alfred-workflows#90]
Title.

**Comment by vitorgalvao** [comment]
Some authors do it, but I don’t. I share and continue to support over fifty Workflows, and keeping two or more versions of each is too much work for something I do for free.

I’ll soon have a sponsorship option with contribution tiers on this repo, but it wouldn’t make sense making supporting older versions one of them — if you can afford a contribution to me, you can afford the latest version of Alfred.

If you need a version of one of my Workflows for Alfred 3, some may still work because they did not require modification for Alfred 4. Otherwise, you’ll need to find the relevant commit, download that version (the last compatible one for your version of Alfred), and delete the `OneUpdater` node so it never tries to auto-update.
