### ISSUE TITLE
Changing Workflow Icons

### ISSUE THREAD

**Issue by KarlPiper** [vitorgalvao/alfred-workflows#93]
How would one go about changing the icons used by a workflow?

I know that you can drag-and-drop a new 'main' icon from the workflows editor.

DenteAzul, for example, only has two icons. The 'offline/alt' icon would be the one that needs to be changed, all instances of the default icon are replaced by the drag-and-drop I mentioned before.

**Comment by vitorgalvao** [comment]
There is no standard way of changing a Workflow’s icons; it depends on the Workflow. This bug tracker is for support on my own Workflows, not general Alfred questions.

Why do you want to change the icons, anyway?

Last time I saw that someone had changed the icons in one of my Workflows, they also changed the authorship and were passing it off as their own — which is illegal, because even works in the public domain have a recognised author that cannot be changed.

**Comment by KarlPiper** [comment]
Thanks for your time.

**Comment by vitorgalvao** [comment]
> Thanks for your time.

You’re welcome. Apologies if I sounded too blunt, but I’m sick so I’m lacking the wherewithal to mince words. In no way do I mean to imply you’d do the same as the other person. What they did was crummy, but I haven’t changed my licenses because I believe most people wouldn’t do the same.

But it continues to be true there’s no standard way to change the icons included in a Workflow. Apart from a Workflow’s main image, authors are free to choose how to include alternate images. There’s not even a recommended way; I do it differently depending on the Workflow.

I’d still appreciate an answer to my question:

> Why do you want to change the icons, anyway?

**Comment by KarlPiper** [comment]
That's fine, I understand. Your icons are fine, I was just poking around to see how things work, and thought making custom icons would be an easy place to start.
