### ISSUE TITLE
No notifications 

### ISSUE THREAD

**Issue by pavzagor** [vitorgalvao/alfred-workflows#97]
#### Setup info

* Workflow name: WebScreenshot
* Workflow version: 1.6.3
* Alfred version: 4.0.6
* macOS version:10.15.1

#### Description of issue
No notifications, no sounds. Alfred has all the permissions for notifications.

#### Debugger output

```
[21:38:47.771] Logging Started...
[21:38:56.499] WebScreenshot[Keyword] Processing complete
[21:38:56.503] WebScreenshot[Keyword] Passing output '' to Run Script
[21:38:58.239] WebScreenshot[Run Script] Processing complete
[21:38:58.244] WebScreenshot[Run Script] Passing output '' to Run Script
```

**Comment by vitorgalvao** [comment]
> Alfred has all the permissions for notifications.

Alfred isn’t the one showing the notifications, but the `Notificator` app inside the Workflow. I’m guessing Catalina is the one breaking that. If you go to the Workflow’s directory in the Finder, right-click it and pick `Open`, it should work all subsequent times.

I could sign and notarise the apps, but since I’m making and releasing these for free and I don’t have a steady source of income, I can’t justify the expense for the paid developer account.

I may have to change the notification method, but I don’t want to. I’ll think about how to best proceed. Thank you for the report.

**Comment by vitorgalvao** [comment]
> If you go to the Workflow’s directory in the Finder, right-click it and pick `Open`, it should work all subsequent times.

I’d like to know if that worked, if you did it, so I can be certain of what’s causing the issue.

**Comment by gandalfsaxe** [comment]
Worked for me (#105). I thought I tried it once where it didn't work, not sure what happened. But it worked when I tried again.
